# Generated by Django 5.1.3 on 2024-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silentmarket', '0003_alter_productimg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='url',
            field=models.TextField(),
        ),
    ]
