# Generated by Django 5.1.3 on 2024-11-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silentmarket', '0004_alter_productimg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=3000, max_digits=10, verbose_name='배송비'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='url',
            field=models.TextField(verbose_name='이미지주소'),
        ),
    ]
