# Generated by Django 5.1.3 on 2024-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silentmarket', '0005_alter_product_shipping_cost_alter_productimg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=3500, max_digits=10, verbose_name='배송비'),
        ),
    ]
